name: Release

on:
  push:
    paths:
      - '.storybook/**'
      - '.changeset/**'
      - 'packages/**'
      - 'stories/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build
        run: pnpm build

      # - name: Generate Docs
      #   run: pnpm gen:docs

      - name: Create release PR or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'ci(changesets): version packages'
          setupGitUser: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create @dev release
        if: steps.changesets.outputs.published != 'true'
        run: |
          git checkout main
          pnpm version:dev
          pnpm release:dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Changelog
        if: steps.changesets.outputs.published == 'true'
        run: |
          pnpm changelog:latest
          pnpm changelog:format
          pnpm changelog:commit

      - name: Notification Mattermost and Discord
        if: steps.changesets.outputs.published == 'true'
        run: |
          pnpm release:mattermost
          pnpm release:discord
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Build Storybook
        if: steps.changesets.outputs.published == 'true'
        run: pnpm build-storybook

      - name: Update Storybook
        if: steps.changesets.outputs.published == 'true'
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages
          folder: storybook-static
