name: Release

on: [workflow_dispatch]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get PNPM
        id: pnpm-cache
        run: echo "::set-output name=dir::$(pnpm cache dir)"

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Setup Git user
        shell: bash
        run: |
          git config --global user.email "hirotomo.yamada@avap.co.jp"
          git config --global user.name "hirotomoyamada"

      - name: Create branch
        run: |
          git checkout -b changeset-release/main

      - name: Update Yamada UI
        run: pnpm up '@yamada-ui/*' --latest

      - name: Commit package.json
        run: |
          git add package.json pnpm-lock.yaml
          git diff --staged --quiet || git commit -m "ci(changesets): $GITHUB_SHA"
          git push origin changeset-release/main

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: 'Version Packages'
          branch: changeset-release/main
