name: Test

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Collaborators
        run: pnpm tsx scripts/test.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
